<?php
/**
 * Implements hook_theme().
 */
function devbranch_task_theme($existing, $type, $theme, $path) {
  $variables = [
    'devbranch_task' => [
      'variables' => [
        'source_text' => NULL,
      ],
      'template' => 'devbranch_task',
    ],
    'devbranch_task_menu' => [
      'variables' => [
        'source_links' => NULL,
      ],
      'template' => 'devbranch_task_menu',
    ],
  ];
  return $variables;
}
